# Generated by Django 4.0.4 on 2023-06-29 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao_app', '0004_remove_validacao_emails_alter_validacao_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailConfirmacao',
        ),
        migrations.DeleteModel(
            name='Validacao',
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votacao_app.grupo'),
        ),
    ]
