# Generated by Django 4.1.1 on 2023-07-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "votacao_app",
            "0005_aluno_grupo_delete_emailconfirmacao_delete_validacao_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="grupo",
            old_name="nome",
            new_name="nome_grupo",
        ),
    ]
