# Generated by Django 4.1.1 on 2023-07-01 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votacao_app", "0006_rename_nome_grupo_nome_grupo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="votacao_app.grupo"
            ),
        ),
    ]
