# Generated by Django 4.1.1 on 2023-07-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votacao_app", "0008_votacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votacao",
            name="aluno",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="votacao_app.aluno"
            ),
        ),
    ]
