# Generated by Django 4.1.1 on 2023-07-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votacao_app", "0009_alter_votacao_aluno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votacao",
            name="aluno",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="votacao",
            name="grupo",
            field=models.CharField(max_length=30),
        ),
    ]
